### ISSUE TITLE
Rings Shows Relics

### ISSUE THREAD

**Issue by KLEPTOROTH** [ynzenu/MysticCraftingFeedback#2]
Self explanatory, the rings menu shows relics, and relics shows backpacks:
![image](https://github.com/user-attachments/assets/0c494ce9-42ec-43f3-aa02-711c58ca17b8)
![image](https://github.com/user-attachments/assets/966dc8f3-1f2f-4d1f-b50c-198fbba79ded)

**Comment by gooseears** [comment]
In addition, there are several ring and relic items missing.  Conflux legendary ring cannot be found in any category, for example.

**Comment by ynzenu** [comment]
Thank you both. This issue was fixed in version 1.4.1
